@startuml
participant Actor

Actor -> AbstractBootstrap : doBind
activate AbstractBootstrap

AbstractBootstrap -> AbstractBootstrap : <color:#228B22>1 initAndRegister</color>
activate AbstractBootstrap
AbstractBootstrap --> AbstractBootstrap
deactivate AbstractBootstrap

== 1 initAndRegister start ==
AbstractBootstrap -> ChannelFactory : <color:#009ACD>1.1 newChannel</color>
activate ChannelFactory
ChannelFactory --> AbstractBootstrap
deactivate ChannelFactory

activate ServerBootstrap

AbstractBootstrap -> ServerBootstrap : <color:#009ACD>1.2 init</color> \n <color:#009ACD>调用子类实现的init方法</color>
activate ServerBootstrap
ServerBootstrap --> AbstractBootstrap
deactivate ServerBootstrap

== 1.2 init start==
ServerBootstrap [#EE7621]-> AbstractBootstrap : \n 1.2.1 setChannelOptions \n 调用父类的setChannelOptions方法
activate AbstractBootstrap
AbstractBootstrap --> ServerBootstrap
deactivate AbstractBootstrap

ServerBootstrap [#EE7621]-> AbstractBootstrap : \n 1.2.2 setAttributes \n 调用父类的setAttributes方法
activate AbstractBootstrap
AbstractBootstrap --> ServerBootstrap
deactivate AbstractBootstrap

ServerBootstrap -> AbstractChannel : 1.2.3 pipeline
activate AbstractChannel
AbstractChannel --> ServerBootstrap
deactivate AbstractChannel

ServerBootstrap -> ServerBootstrapAcceptor : \n 1.2.4 create and add to serverSocketChannel
activate ServerBootstrapAcceptor
ServerBootstrapAcceptor --> ServerBootstrap
deactivate ServerBootstrapAcceptor

== init end ==

AbstractBootstrap -> EventLoopGroup : <color:#009ACD>1.3 register</color>
activate EventLoopGroup
EventLoopGroup --> AbstractBootstrap
deactivate EventLoopGroup

'== 1.3 register start==
'== 1.3 register end==

== initAndRegister end ==


'alt 注册完成并且成功
'    AbstractBootstrap -> AbstractBootstrap : \n 2 doBind
'    activate AbstractBootstrap
'    AbstractBootstrap --> AbstractBootstrap
'    deactivate AbstractBootstrap
'else 异步,此时注册还没有完成,但总是会完成的
'    AbstractBootstrap -> AbstractBootstrap : \n 2 doBind
'    activate AbstractBootstrap
'    AbstractBootstrap --> AbstractBootstrap
'    deactivate AbstractBootstrap
'end

return
@enduml