@startuml participant

Actor -> NioEventLoopGroup: \n\n 1. new NioEventLoopGroup(); \n    创建 NioEventLoopGroup 对象

NioEventLoopGroup -> MultithreadEventLoopGroup: \n\n 2. super 向上调用父类构造器

MultithreadEventLoopGroup -> MultithreadEventExecutorGroup: \n\n 3. super 向上调用父类构造器

group MultithreadEventExecutorGroup构造器中的逻辑

    MultithreadEventExecutorGroup -> MultithreadEventExecutorGroup: \n\n

end

Actor <-- NioEventLoopGroup
@enduml