@startuml participant

Actor -> NioEventLoop: 1 create

NioEventLoop -> SingleThreadEventLoop: 2 调用父类构造器
SingleThreadEventLoop -> SingleThreadEventExecutor: 3 调用父类构造器
SingleThreadEventExecutor -> xxxParent :4 调用父类构造器
SingleThreadEventExecutor -> SingleThreadEventExecutor : 4.1 \n 初始化NioEventLoop内部任务队列
SingleThreadEventExecutor -> SingleThreadEventExecutor : 4.2 \n 初始化其他参数

SingleThreadEventLoop <-- SingleThreadEventExecutor
NioEventLoop <-- SingleThreadEventLoop

NioEventLoop -> NioEventLoop : \n 2.1 创建selector
NioEventLoop -> NioEventLoop : \n 2.2 初始化其他相关参数

Actor <-- NioEventLoop
@enduml