@startuml participant

Actor -> NioEventLoop: 1 create

NioEventLoop -> NioEventLoop: \n 1.1 初始化 NioEventLoop 内部任务队列
NioEventLoop -> SingleThreadEventLoop: \n 2 调用父类构造器
SingleThreadEventLoop -> SingleThreadEventExecutor: 3 调用父类构造器
SingleThreadEventExecutor -> xxxParent :4 调用父类构造器
SingleThreadEventExecutor -> SingleThreadEventExecutor : \n 4.1 初始化其他参数

SingleThreadEventLoop <-- SingleThreadEventExecutor
NioEventLoop <-- SingleThreadEventLoop

NioEventLoop -> NioEventLoop : \n 2.1 创建selector
NioEventLoop -> NioEventLoop : \n 2.2 初始化其他相关参数

Actor <-- NioEventLoop
@enduml