@startuml

Actor -> AbstractBootstrap: doBind

AbstractBootstrap -> AbstractBootstrap: \n ① validate \n     启动校验

AbstractBootstrap -> AbstractBootstrap: \n ② doBind \n     核心业务逻辑

    group #FDF5E6 doBind
        AbstractBootstrap -> AbstractBootstrap: \n\n initAndRegister

            group #F0FFF0 initAndRegister

            AbstractBootstrap -> ServerBootstrap: init
            AbstractBootstrap -> AbstractBootstrap: register

            end

        AbstractBootstrap -> AbstractBootstrap: \n\n doBind0
    end

'AbstractBootstrap -> AbstractBootstrap: \n\n\n initAndRegister
'    group  #LightBlue initAndRegister
'        AbstractBootstrap -> ReflectiveChannelFactory: \n\n newChannel
'        ReflectiveChannelFactory --> AbstractBootstrap:
'
'        AbstractBootstrap -> ServerBootstrap: \n\n init 初始化channel
'
'        AbstractBootstrap -> AbstractBootstrap: \n\n register
'    end
'
'
'AbstractBootstrap -> AbstractBootstrap: \n\n\n doBind0
'    group #Pink doBind0
'
'    end
'



@enduml